### ISSUE TITLE
pwauth called for every request

### ISSUE THREAD

**Issue by giray** [phokz/pwauth#9]
So this may not be directly a pwauth question ...

I have pwauth (2.3.10) running with apache 2.4.6 and authnz-external-3.3.1.  
Everything works fine, however, I see in the auth logs that pwauth is being called
for every GET request.  There is no re-authentication request and the application
works fine, but I would kind of expect that apache would "remember" that session
to be authenticated, and not re-authenticate constantly, which creates quite a 
bit of overhead.

Any pointers welcome, my config is as follows

```
<Location /test>
     AuthFormProvider external
     AuthExternal pwauth
     GroupExternal ugroup


     AuthType form
     AuthName "Secret Area"
     Session On
     SessionCookieName session path=/test

     <RequireAll>
     require valid-user
        <RequireAny>
           require external-group app_access_grp
        </RequireAny>

     </RequireAll>

</Location>
```

**Comment by phokz** [comment]
Hi, is this an issue of mod_authnz_external or is it an issue with AuthType form?
It seems that AuthType form just stores credentials in session store, and they are revalidated on every request no matter what auth provider is used.

**Comment by giray** [comment]
Found the solution as follows.  Using AuthFormSitePassphrase allows keeping track of the session information. and does not repeatedly check for authentication in the background

```
<Location /test>
     AuthFormProvider external
     AuthFormFakeBasicAuth On
     AuthFormSitePassphrase <Random String>



     AuthExternal pwauth
     GroupExternal ugroup


     AuthType form
     AuthName "Secret Area"
     Session On
     SessionEnv On

     SessionCryptoPassphrase <RANDOM STRING!!!>
     SessionCookieName session path=/test;httponly;secure;

     # Require an authenticated users that is either in sg-security or sg-networking
     <RequireAll>
     require valid-user
        <RequireAny>
           require external-group group1
           require external-group group2
        </RequireAny>

     </RequireAll>

</Location>
```
